In [11]:
import torch
import numpy as np

# PyTorch works with "tensors"

Tensors are a specific data structure that contain n-dimensional arrays (like numpy) but also a lot of metadata.
Primarily, they can keep track of every 'operation' done to them and maintain a computational graph.

This enables automatic differentiation -> crucial for deep learning

In [5]:
a = torch.tensor([10, 20])

In [7]:
a, a.shape


(tensor([10, 20]), torch.Size([2]))

In [9]:
b = torch.tensor([5, 2])
b

tensor([5, 2])

In [10]:
a*b

tensor([50, 40])